### ISSUE TITLE
Solution / Project does not build after git clone and Nuget package restore

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.OData.OAuth#3]
When I open the solution (after cloning the repo) and downloading the missing packages I get the following build errors:

![image](https://cloud.githubusercontent.com/assets/8310360/11263739/cf91f320-8e8d-11e5-8d2a-4cbe27cf5db8.png)

@rufer7 could you pls try this on your machine as well?

**Comment by rufer7** [comment]
same here. The question is, why the nuget.exe is in the .nuget folder.

**Comment by rufer7** [comment]
@dfch Works now on my machine as well after cleanup. I also finished the feature branch so you can now check out the branch `develop` and build it.
