### ISSUE TITLE
Build OAuth client o call API (PAP) through API broker

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.OData.OAuth#5]
To call PAP API through API Broker a OAuth2 Authentication Token is needed. JWT token works only if the services can be accessed directly
* [x] Find out if it would be possible to send the endusers OAuth token throup API broker to managed services API 
-> Mail sent to Christoph Mathis
* [x] create a PAP service client to use in code

**Comment by ChrEggenberger** [comment]
We always use the ManagedService User to call ohter API's. An Acces token can be refreshd using a manually creates refresh token which will not change. Therfore it can be saved in the Appclusive Key-Value store
see https://wiki.swisscom.com/display/ETA/Permissions+and+Authentication (thers is not much there yet :-) )

**Comment by ChrEggenberger** [comment]
For all APiBroker calls I creted the project biz.dfch.CS.ApiBroker.Client  there is a ApiBrokerRequest class which can be used and done.

Todo:
* [ ] load all permission for all roles

**Comment by dfch** [comment]
@ChrEggenberger is this task finished? we already made a release on Friday; is this already implemented?

**Comment by rufer7** [comment]
permission and role loading is implemented in the filter of the appclusive project so I'll close this issue
