### ISSUE TITLE
JWT-Library supports only HSxxx algorithms although http://jwt.io/ says it would, but API Broker is using RS256

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.OData.OAuth#6]
-> use other library

switch (algorithm) 
252             { 
253                 case "HS256": return JwtHashAlgorithm.HS256; 
254                 case "HS384": return JwtHashAlgorithm.HS384; 
255                 case "HS512": return JwtHashAlgorithm.HS512; 
256                 default: throw new SignatureVerificationException("Algorithm not supported."); 
257             }

**Comment by dfch** [comment]
could you please use the Microsoft supplied .NET library (somewhere in the `Identity` namespace) if possible? or are there any reasons against it?

**Comment by ChrEggenberger** [comment]
Have bei der ersten Runde nicht das genommen Weil much die Doku nicht ganz überzeugt hat.
https://msdn.microsoft.com/en-us/library/dn383568(v=vs.110).aspx
Auch sonst ist kaum etwas zu finds. Habs aber heute Nachmittag noch einmal angeschaut und testhalber mal installiert. Sooo gross IST die Auswahl nicht

Das Andere ist auf Git und der Code nicht sehr komplex. Ev ist es gar einfacher dort die Validation mit RS256 Verschlüsselung einzubauen

Viele Grüsse
Christian
________________________________
Von: Ronald Rink<mailto:notifications@github.com>
Gesendet: ‎20.‎11.‎2015 20:53
An: dfensgmbh/biz.dfch.CS.OData.OAuth<mailto:biz.dfch.CS.OData.OAuth@noreply.github.com>
Cc: Christian Eggenberger<mailto:eggenberger@afca.ch>
Betreff: Re: [biz.dfch.CS.OData.OAuth] JWT-Library supports only HSxxx algorithms although http://jwt.io/ says it would, but API Broker is using RS256 (#6)


could you please use the Microsoft supplied .NET library (somewhere in the Identity namespace) if possible? or are there any reasons against it?

**Comment by ChrEggenberger** [comment]
Use System.IdentityModel.Tokens.Jwt to read JWT token
but no validation implemented yet -> Issue
