### ISSUE TITLE
Validation of signature of JWT is missing

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.OData.OAuth#8]

**Comment by dfch** [comment]
@ChrEggenberger do you know when this will be implemented?

**Comment by ChrEggenberger** [comment]
I use System.IdentityModel.Tokens.Jwt to read JWT token now (see issue #6) 
What we need now is the right keys to validate the token. But I think this issue has lower priority than solving all the questions about how permissions work.

**Comment by ChrEggenberger** [comment]
Mail Christoph Mathis: 

den Public key ist über eine Api für dich zur verfügung gestellt.
Die API ist unter https://cmabrmp-lab3ch-1.mgmt.sccloudpoc.net:9001/v1/accessbroker/jwk_uri

Da solltest du den public key bekommen.

**Comment by rufer7** [comment]
this issue gets tracked directly in the appclusive project dfch/biz.dfch.CS.Appclusive#141
