### ISSUE TITLE
Test and verify setting change permissions on VM or system in PAP

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.OData.OAuth#9]

**Comment by ChrEggenberger** [comment]
Stand der Dinge:

1.	Permission für 1 Maschine abrufen
https://{{apigee}}:9001/v1/pap/nodes/{{machineId}}/policies
OK

2.	Unterbrechen der Rechte Vererbung für die Maschine
PUT auf https://cmabrmp-lab3ch-1.mgmt.sccloudpoc.net:9001/v1/pap/nodes/64f680a6-659b-4c14-85a5-bf60a2181fcc/disable_inheritance
Das Mapping fehlt noch auf dem APIGEE. Wird am Montag eingerichtet.
siehe https://wiki.swisscom.com/display/ETA/Mapped+Endpoint+in+Apigee 

3.	Setzen einer permission auf der Maschine für 1 rolle
POST https://{{apigee}}:9001/v1/pap/nodes/{{machineId}}/policies
Fehler, vermutlich weil 2 schon nicht möglich ist

**Comment by ChrEggenberger** [comment]
* enable/disable inheritance is not available yet
* POST policies resolved
* new problem: delete policy runs without errors (and job successful), but does not remove the policy

**Comment by dfch** [comment]
@ChrEggenberger when done with your tests (from yesterday?) pls update issue

**Comment by rufer7** [comment]
@dfch @ChrEggenberger or even better track the status directly in the new repository [biz.dfch.CS.Scs.Cmp.Pap.Client](https://github.com/dfensgmbh/biz.dfch.CS.Scs.Cmp.Pap.Client)

**Comment by dfch** [comment]
@ChrEggenberger good for me, after you created the issue in the new repository pls close this issue and link to it
